/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as fxEngineSol from "./FXEngine.sol";
export type { fxEngineSol };
import type * as payrollEngineSol from "./PayrollEngine.sol";
export type { payrollEngineSol };
export type { LoanPool } from "./LoanPool";
export type { MockOracle } from "./MockOracle";
export type { MockToken } from "./MockToken";
export type { ReputationScore } from "./ReputationScore";
