/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface ReputationScoreInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "authorized"
      | "decreaseScore"
      | "getScore"
      | "increaseScore"
      | "owner"
      | "setAuthorized"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic: "Authorized" | "ScoreDecreased" | "ScoreIncreased"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "authorized",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "decreaseScore",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getScore",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "increaseScore",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "setAuthorized",
    values: [AddressLike, boolean]
  ): string;

  decodeFunctionResult(functionFragment: "authorized", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "decreaseScore",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getScore", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "increaseScore",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "setAuthorized",
    data: BytesLike
  ): Result;
}

export namespace AuthorizedEvent {
  export type InputTuple = [contractAddress: AddressLike, status: boolean];
  export type OutputTuple = [contractAddress: string, status: boolean];
  export interface OutputObject {
    contractAddress: string;
    status: boolean;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ScoreDecreasedEvent {
  export type InputTuple = [user: AddressLike, newScore: BigNumberish];
  export type OutputTuple = [user: string, newScore: bigint];
  export interface OutputObject {
    user: string;
    newScore: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ScoreIncreasedEvent {
  export type InputTuple = [user: AddressLike, newScore: BigNumberish];
  export type OutputTuple = [user: string, newScore: bigint];
  export interface OutputObject {
    user: string;
    newScore: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface ReputationScore extends BaseContract {
  connect(runner?: ContractRunner | null): ReputationScore;
  waitForDeployment(): Promise<this>;

  interface: ReputationScoreInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  authorized: TypedContractMethod<[arg0: AddressLike], [boolean], "view">;

  decreaseScore: TypedContractMethod<
    [user: AddressLike, amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  getScore: TypedContractMethod<[user: AddressLike], [bigint], "view">;

  increaseScore: TypedContractMethod<
    [user: AddressLike, amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  owner: TypedContractMethod<[], [string], "view">;

  setAuthorized: TypedContractMethod<
    [caller: AddressLike, status: boolean],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "authorized"
  ): TypedContractMethod<[arg0: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "decreaseScore"
  ): TypedContractMethod<
    [user: AddressLike, amount: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "getScore"
  ): TypedContractMethod<[user: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "increaseScore"
  ): TypedContractMethod<
    [user: AddressLike, amount: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "setAuthorized"
  ): TypedContractMethod<
    [caller: AddressLike, status: boolean],
    [void],
    "nonpayable"
  >;

  getEvent(
    key: "Authorized"
  ): TypedContractEvent<
    AuthorizedEvent.InputTuple,
    AuthorizedEvent.OutputTuple,
    AuthorizedEvent.OutputObject
  >;
  getEvent(
    key: "ScoreDecreased"
  ): TypedContractEvent<
    ScoreDecreasedEvent.InputTuple,
    ScoreDecreasedEvent.OutputTuple,
    ScoreDecreasedEvent.OutputObject
  >;
  getEvent(
    key: "ScoreIncreased"
  ): TypedContractEvent<
    ScoreIncreasedEvent.InputTuple,
    ScoreIncreasedEvent.OutputTuple,
    ScoreIncreasedEvent.OutputObject
  >;

  filters: {
    "Authorized(address,bool)": TypedContractEvent<
      AuthorizedEvent.InputTuple,
      AuthorizedEvent.OutputTuple,
      AuthorizedEvent.OutputObject
    >;
    Authorized: TypedContractEvent<
      AuthorizedEvent.InputTuple,
      AuthorizedEvent.OutputTuple,
      AuthorizedEvent.OutputObject
    >;

    "ScoreDecreased(address,uint256)": TypedContractEvent<
      ScoreDecreasedEvent.InputTuple,
      ScoreDecreasedEvent.OutputTuple,
      ScoreDecreasedEvent.OutputObject
    >;
    ScoreDecreased: TypedContractEvent<
      ScoreDecreasedEvent.InputTuple,
      ScoreDecreasedEvent.OutputTuple,
      ScoreDecreasedEvent.OutputObject
    >;

    "ScoreIncreased(address,uint256)": TypedContractEvent<
      ScoreIncreasedEvent.InputTuple,
      ScoreIncreasedEvent.OutputTuple,
      ScoreIncreasedEvent.OutputObject
    >;
    ScoreIncreased: TypedContractEvent<
      ScoreIncreasedEvent.InputTuple,
      ScoreIncreasedEvent.OutputTuple,
      ScoreIncreasedEvent.OutputObject
    >;
  };
}
