/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IFXEngine,
  IFXEngineInterface,
} from "../../../contracts/PayrollEngine.sol/IFXEngine";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "tokenIn",
        type: "address",
      },
      {
        internalType: "address",
        name: "tokenOut",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "amountIn",
        type: "uint256",
      },
    ],
    name: "convert",
    outputs: [
      {
        internalType: "uint256",
        name: "amountOut",
        type: "uint256",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class IFXEngine__factory {
  static readonly abi = _abi;
  static createInterface(): IFXEngineInterface {
    return new Interface(_abi) as IFXEngineInterface;
  }
  static connect(address: string, runner?: ContractRunner | null): IFXEngine {
    return new Contract(address, _abi, runner) as unknown as IFXEngine;
  }
}
