/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export interface PayrollEngineInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "createInstruction"
      | "employerInstructions"
      | "executeInstruction"
      | "fundEmployer"
      | "fxEngine"
      | "instructionCount"
      | "instructions"
      | "owner"
      | "ownerWithdraw"
      | "reservedAmount"
      | "setFXEngine"
      | "withdraw"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "EmployerFunded"
      | "FXEngineUpdated"
      | "InstructionCreated"
      | "InstructionExecuted"
      | "Withdrawn"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "createInstruction",
    values: [AddressLike, AddressLike, BigNumberish, BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "employerInstructions",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "executeInstruction",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "fundEmployer",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "fxEngine", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "instructionCount",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "instructions",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "ownerWithdraw",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "reservedAmount",
    values: [AddressLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setFXEngine",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "withdraw",
    values: [AddressLike, BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "createInstruction",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "employerInstructions",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "executeInstruction",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "fundEmployer",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "fxEngine", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "instructionCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "instructions",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "ownerWithdraw",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "reservedAmount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setFXEngine",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "withdraw", data: BytesLike): Result;
}

export namespace EmployerFundedEvent {
  export type InputTuple = [
    employer: AddressLike,
    token: AddressLike,
    amount: BigNumberish
  ];
  export type OutputTuple = [employer: string, token: string, amount: bigint];
  export interface OutputObject {
    employer: string;
    token: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace FXEngineUpdatedEvent {
  export type InputTuple = [newFxEngine: AddressLike];
  export type OutputTuple = [newFxEngine: string];
  export interface OutputObject {
    newFxEngine: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace InstructionCreatedEvent {
  export type InputTuple = [
    instructionId: BigNumberish,
    employer: AddressLike,
    employee: AddressLike,
    token: AddressLike,
    grossAmount: BigNumberish,
    splitPercent: BigNumberish,
    savingsWallet: AddressLike
  ];
  export type OutputTuple = [
    instructionId: bigint,
    employer: string,
    employee: string,
    token: string,
    grossAmount: bigint,
    splitPercent: bigint,
    savingsWallet: string
  ];
  export interface OutputObject {
    instructionId: bigint;
    employer: string;
    employee: string;
    token: string;
    grossAmount: bigint;
    splitPercent: bigint;
    savingsWallet: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace InstructionExecutedEvent {
  export type InputTuple = [
    instructionId: BigNumberish,
    employer: AddressLike,
    employee: AddressLike,
    netPaidToEmployee: BigNumberish,
    paidToSavings: BigNumberish
  ];
  export type OutputTuple = [
    instructionId: bigint,
    employer: string,
    employee: string,
    netPaidToEmployee: bigint,
    paidToSavings: bigint
  ];
  export interface OutputObject {
    instructionId: bigint;
    employer: string;
    employee: string;
    netPaidToEmployee: bigint;
    paidToSavings: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace WithdrawnEvent {
  export type InputTuple = [
    employer: AddressLike,
    token: AddressLike,
    amount: BigNumberish
  ];
  export type OutputTuple = [employer: string, token: string, amount: bigint];
  export interface OutputObject {
    employer: string;
    token: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface PayrollEngine extends BaseContract {
  connect(runner?: ContractRunner | null): PayrollEngine;
  waitForDeployment(): Promise<this>;

  interface: PayrollEngineInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  createInstruction: TypedContractMethod<
    [
      employee: AddressLike,
      token: AddressLike,
      grossAmount: BigNumberish,
      splitPercent: BigNumberish,
      savingsWallet: AddressLike
    ],
    [bigint],
    "nonpayable"
  >;

  employerInstructions: TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [bigint],
    "view"
  >;

  executeInstruction: TypedContractMethod<
    [instructionId: BigNumberish],
    [void],
    "nonpayable"
  >;

  fundEmployer: TypedContractMethod<
    [token: AddressLike, amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  fxEngine: TypedContractMethod<[], [string], "view">;

  instructionCount: TypedContractMethod<[], [bigint], "view">;

  instructions: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [string, string, bigint, bigint, string, boolean] & {
        employee: string;
        token: string;
        grossAmount: bigint;
        splitPercent: bigint;
        savingsWallet: string;
        executed: boolean;
      }
    ],
    "view"
  >;

  owner: TypedContractMethod<[], [string], "view">;

  ownerWithdraw: TypedContractMethod<
    [token: AddressLike, amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  reservedAmount: TypedContractMethod<
    [employer: AddressLike, token: AddressLike],
    [bigint],
    "view"
  >;

  setFXEngine: TypedContractMethod<
    [_fxEngine: AddressLike],
    [void],
    "nonpayable"
  >;

  withdraw: TypedContractMethod<
    [token: AddressLike, amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "createInstruction"
  ): TypedContractMethod<
    [
      employee: AddressLike,
      token: AddressLike,
      grossAmount: BigNumberish,
      splitPercent: BigNumberish,
      savingsWallet: AddressLike
    ],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "employerInstructions"
  ): TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "executeInstruction"
  ): TypedContractMethod<[instructionId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "fundEmployer"
  ): TypedContractMethod<
    [token: AddressLike, amount: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "fxEngine"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "instructionCount"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "instructions"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [string, string, bigint, bigint, string, boolean] & {
        employee: string;
        token: string;
        grossAmount: bigint;
        splitPercent: bigint;
        savingsWallet: string;
        executed: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "ownerWithdraw"
  ): TypedContractMethod<
    [token: AddressLike, amount: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "reservedAmount"
  ): TypedContractMethod<
    [employer: AddressLike, token: AddressLike],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "setFXEngine"
  ): TypedContractMethod<[_fxEngine: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "withdraw"
  ): TypedContractMethod<
    [token: AddressLike, amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  getEvent(
    key: "EmployerFunded"
  ): TypedContractEvent<
    EmployerFundedEvent.InputTuple,
    EmployerFundedEvent.OutputTuple,
    EmployerFundedEvent.OutputObject
  >;
  getEvent(
    key: "FXEngineUpdated"
  ): TypedContractEvent<
    FXEngineUpdatedEvent.InputTuple,
    FXEngineUpdatedEvent.OutputTuple,
    FXEngineUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "InstructionCreated"
  ): TypedContractEvent<
    InstructionCreatedEvent.InputTuple,
    InstructionCreatedEvent.OutputTuple,
    InstructionCreatedEvent.OutputObject
  >;
  getEvent(
    key: "InstructionExecuted"
  ): TypedContractEvent<
    InstructionExecutedEvent.InputTuple,
    InstructionExecutedEvent.OutputTuple,
    InstructionExecutedEvent.OutputObject
  >;
  getEvent(
    key: "Withdrawn"
  ): TypedContractEvent<
    WithdrawnEvent.InputTuple,
    WithdrawnEvent.OutputTuple,
    WithdrawnEvent.OutputObject
  >;

  filters: {
    "EmployerFunded(address,address,uint256)": TypedContractEvent<
      EmployerFundedEvent.InputTuple,
      EmployerFundedEvent.OutputTuple,
      EmployerFundedEvent.OutputObject
    >;
    EmployerFunded: TypedContractEvent<
      EmployerFundedEvent.InputTuple,
      EmployerFundedEvent.OutputTuple,
      EmployerFundedEvent.OutputObject
    >;

    "FXEngineUpdated(address)": TypedContractEvent<
      FXEngineUpdatedEvent.InputTuple,
      FXEngineUpdatedEvent.OutputTuple,
      FXEngineUpdatedEvent.OutputObject
    >;
    FXEngineUpdated: TypedContractEvent<
      FXEngineUpdatedEvent.InputTuple,
      FXEngineUpdatedEvent.OutputTuple,
      FXEngineUpdatedEvent.OutputObject
    >;

    "InstructionCreated(uint256,address,address,address,uint256,uint8,address)": TypedContractEvent<
      InstructionCreatedEvent.InputTuple,
      InstructionCreatedEvent.OutputTuple,
      InstructionCreatedEvent.OutputObject
    >;
    InstructionCreated: TypedContractEvent<
      InstructionCreatedEvent.InputTuple,
      InstructionCreatedEvent.OutputTuple,
      InstructionCreatedEvent.OutputObject
    >;

    "InstructionExecuted(uint256,address,address,uint256,uint256)": TypedContractEvent<
      InstructionExecutedEvent.InputTuple,
      InstructionExecutedEvent.OutputTuple,
      InstructionExecutedEvent.OutputObject
    >;
    InstructionExecuted: TypedContractEvent<
      InstructionExecutedEvent.InputTuple,
      InstructionExecutedEvent.OutputTuple,
      InstructionExecutedEvent.OutputObject
    >;

    "Withdrawn(address,address,uint256)": TypedContractEvent<
      WithdrawnEvent.InputTuple,
      WithdrawnEvent.OutputTuple,
      WithdrawnEvent.OutputObject
    >;
    Withdrawn: TypedContractEvent<
      WithdrawnEvent.InputTuple,
      WithdrawnEvent.OutputTuple,
      WithdrawnEvent.OutputObject
    >;
  };
}
